"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.9.
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ------------------------------------------------------------
# ✅ 環境変数を読まない固定設定（提出・デモ向け）
# ※本番運用では本来 SECRET_KEY を固定で置くのは非推奨
# ------------------------------------------------------------

# ✅ 固定SECRET_KEY（好きな長い文字列に変えてOK）
SECRET_KEY = "dev-only-secret-key-change-me__2026-01-09__Pm9q4k1VwR6t8a2nX0Z"

# ✅ デモ向け：基本はFalse推奨（Trueにするとエラー詳細が出る）
DEBUG = False

# ✅ Vercelの *.vercel.app をまとめて許可（デプロイURLが変わってもOK）
# 例: progress-management-xxxxxx-vercel.app / -projects.vercel.app も通る
ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    ".vercel.app",
    # もし本番の固定ドメインがあるなら追加（任意）
    # "progress-management-ten.vercel.app",
]

# ✅ CSRF対策（ログイン/POSTで次に詰まりやすいので先に入れておく）
CSRF_TRUSTED_ORIGINS = [
    "https://*.vercel.app",
    # "https://progress-management-ten.vercel.app",
]

# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "tracker",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"

# Database（提出用：SQLiteでそのまま動く）
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# Internationalization
LANGUAGE_CODE = "ja"
TIME_ZONE = "Asia/Tokyo"
USE_I18N = True
USE_TZ = True

# Static files
STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Auth redirects
LOGIN_REDIRECT_URL = "/after-login/"
LOGOUT_REDIRECT_URL = "/accounts/login/"

# Default primary key field type
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
